version: "2"
services:
  webapi:
    container_name: webapi
    restart: always
    build: ./RenderIt-back
    depends_on:
      - "mongo"
    ports:
      - "4000:4000"
    volumes:
      - ./RenderIt-back:/usr/src/webapi
    network_mode: host

  website:
    container_name: website
    restart: always
    build: ./RenderIt-front
    depends_on:
      - "mongo"
    ports:
      - "3000:3000"
    volumes:
      - ./RenderIt-front:/usr/src/website
    network_mode: host

  mongo:
    container_name: mongo
    image: mongo:4.0.3
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    network_mode: host
  